### PR TITLE
Add multiple blocks and block dragging

### PR DESCRIPTION
**Pull request by pkhead**
I added a Block class and an array to hold Blocks so that multiple blocks can easily be created. Also, do you have a preferred code style? Like for one, would you prefer `snake_case` or `camelCase`? From reading your code so far it appears you don't have a separator between words for each variable, but personally I think that may cause legibility problems. So, for now, I just used `snake_case`.

I've also made some changes to suit my dev environment, namely adding a gitignore for a .vscode folder and adding setup for a lua debugger I use. If you don't have the lua debugger it should run just fine.

(edit 06.07.23 by sabra55: fixed snake_cake to snake_case)

### CODE REVIEW

**Comment by starleaf-luna** [comment]
I'd definitely prefer camel case for vars and other, and snake case in asset names. I thank you for contributing and making things easier, though. :)
also you appear to mispelled "case" in "snake_case" as "cake" the first time and I was confused.

**Review by starleaf-luna — APPROVED** [review]
quick question: why did you expand the block middle part in the spritesheet, then proceed to not do so in the code, keeping it as a 1-pixel quad? approved.

**Comment by pkhead** [comment]
that's because when i stretch out the texture in the block rendering, it becomes more transparent towards the right side because of linear texture filtering.

**Comment by starleaf-luna** [comment]
I see.

**Pull request merged**
